version: "3.9"

services:
  frontend:
    image: nginx
    volumes:
     - nginx_logs:/logs
     - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./frontend/www:/www:ro
     # - ./keys/ssl-dev/:/ssl:ro
    ports:
     - "80:80"
     - "443:443"
    command: [nginx]

  angr:
    build:
      context: backend
      target: angr

  binja:
    build:
      context: backend
      target: binja

  ghidra:
    build:
      context: backend
      target: ghidra

  hexrays:
    build:
      context: backend
      target: hexrays

  reko:
    build:
      context: backend
      target: reko

  retdec:
    build:
      context: backend
      target: retdec

  snowman:
    build:
      context: backend
      target: snowman

volumes:
  nginx_logs:
